### ISSUE TITLE
Game stops working if character touches the edge of the map

### ISSUE THREAD

**Issue by eisbaerBorealis** [TamDenholm/StealTheSun#7]
If I move the character to the edge of the map (just to the edge; not attempting to move beyond the edge), the movement buttons no longer do anything and I can no longer do anything and am forced to refresh the page to start over.

**Comment by TamDenholm** [comment]
Reopening this as the PR merge is 1 tile off. its 4am tho so i'll fix it tomorrow if you dont have time to submit one yourself. thanks!

**Comment by TamDenholm** [comment]
This was resolved by an updated PR.
